trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: covStream
    value: SDSDotNetAPI
  - name: analysisProject
    value: EDS_Analytics_DotNet

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.Name -equals IACA4336910
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

      - template: '/miscellaneous/build_templates/binskim.yml@templates'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
